const BASE_URL = "http://localhost:19191";
const API_BASE_URL = BASE_URL + "/api";
const API_LOGIN_URL = API_BASE_URL + "/login";
const API_ADMIN_BASE_URL = API_BASE_URL + "/admin";
const API_ADMIN_MEMBER_URL = API_ADMIN_BASE_URL + "/member";
const API_ADMIN_PROBLEM_URL = API_ADMIN_BASE_URL + "/problem";
const API_ADMIN_STORY_URL = API_ADMIN_BASE_URL + "/story";
const API_ADMIN_PROGRESS_URL = API_ADMIN_BASE_URL + "/progress";
const API_HOME_URL = API_BASE_URL + "/home";

export {
    BASE_URL,
    API_LOGIN_URL,
    API_ADMIN_MEMBER_URL,
    API_ADMIN_PROBLEM_URL,
    API_ADMIN_STORY_URL,
    API_ADMIN_PROGRESS_URL,
    API_HOME_URL,
}